# Generated by Django 2.2.3 on 2019-08-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numbre',
            new_name='phone_number',
        ),
    ]
